name: Backend CI pipeline

on:
  workflow_dispatch:

jobs:
  backend-build:
    runs-on: aws-ec2-johnnys
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build the app
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Dockerise
        run: |
          docker build -t johnnysta/contacts-application-backend:$GITHUB_RUN_ID -f Dockerfile-backend .

      - name: Backend deploy
        run: |
          docker rm -f contacts-application-backend-container ||true          
          docker run -d -p 8080:8080 --name contacts-application-backend-container johnnysta/contacts-application-backend:$GITHUB_RUN_ID
